# Generated by Django 5.2 on 2025-05-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'Student'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studnet_name',
            new_name='student_name',
        ),
    ]
