# Generated by Django 5.2 on 2025-05-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0006_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='subjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='veggie.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='veggie.subject')),
            ],
            options={
                'verbose_name': 'Subject Marks',
                'ordering': ['student'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
