# Generated by Django 5.2 on 2025-05-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0007_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'ordering': ['student'], 'verbose_name': 'Subject Mark'},
        ),
        migrations.CreateModel(
            name='Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField(default=0)),
                ('date_of_report_card', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='veggie.student')),
            ],
        ),
    ]
