# Generated by Django 5.2 on 2025-05-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0008_alter_subjectmarks_options_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'date_of_report_card')},
        ),
    ]
